webtalk_init -webtalk_dir /media/lite/DATA/E_dissertation/HPRTU/projects/5-XADC_DMA/xadc_pynq/xadc_pynq.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 14 21:16:11 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211051485_1777517049_210632254_868" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fe0bc29befec558c9b44dc5d05ba18ab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ea577ced-cb39-4e61-b565-812dd7e6f658" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3100.093 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 2327616966 -regid "211051485_1777517049_210632254_868" -xml /media/lite/DATA/E_dissertation/HPRTU/projects/5-XADC_DMA/xadc_pynq/xadc_pynq.hw/webtalk/usage_statistics_ext_labtool.xml -html /media/lite/DATA/E_dissertation/HPRTU/projects/5-XADC_DMA/xadc_pynq/xadc_pynq.hw/webtalk/usage_statistics_ext_labtool.html -wdm /media/lite/DATA/E_dissertation/HPRTU/projects/5-XADC_DMA/xadc_pynq/xadc_pynq.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
