# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/design_1_fir_compiler_0_2.xci
# IP: The module: 'design_1_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/design_1_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/design_1_fir_compiler_0_2.xci
# IP: The module: 'design_1_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /media/lite/DATA/E_Dissertation/HPRTU/projects/eLinuxPrj/Prj/2-4_XADC_MultiChannels_Decimation_DMA/xadc_pynq/xadc_pynq.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_2/design_1_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
